// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFqaLTYkJ6zq8oKnzoHo1hr3GFz3x7b3s',
    appId: '1:66711139753:web:2ba02bf36744f1b24f40b8',
    messagingSenderId: '66711139753',
    projectId: 'workout-tracking-app-cf280',
    authDomain: 'workout-tracking-app-cf280.firebaseapp.com',
    storageBucket: 'workout-tracking-app-cf280.firebasestorage.app',
    measurementId: 'G-0PG34CT77D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB98UFQNDeUaY_ZVj95pCDwTyb-KbF76Ig',
    appId: '1:66711139753:android:b3c3c5df7cc0d4384f40b8',
    messagingSenderId: '66711139753',
    projectId: 'workout-tracking-app-cf280',
    storageBucket: 'workout-tracking-app-cf280.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIJGIwf0gYIENs-MZHl1wRVGZaYcVvU7U',
    appId: '1:66711139753:ios:2cc39580ff01428d4f40b8',
    messagingSenderId: '66711139753',
    projectId: 'workout-tracking-app-cf280',
    storageBucket: 'workout-tracking-app-cf280.firebasestorage.app',
    iosBundleId: 'com.example.workoutTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIJGIwf0gYIENs-MZHl1wRVGZaYcVvU7U',
    appId: '1:66711139753:ios:2cc39580ff01428d4f40b8',
    messagingSenderId: '66711139753',
    projectId: 'workout-tracking-app-cf280',
    storageBucket: 'workout-tracking-app-cf280.firebasestorage.app',
    iosBundleId: 'com.example.workoutTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFqaLTYkJ6zq8oKnzoHo1hr3GFz3x7b3s',
    appId: '1:66711139753:web:874f094aea76420f4f40b8',
    messagingSenderId: '66711139753',
    projectId: 'workout-tracking-app-cf280',
    authDomain: 'workout-tracking-app-cf280.firebaseapp.com',
    storageBucket: 'workout-tracking-app-cf280.firebasestorage.app',
    measurementId: 'G-2MM1C1MQKK',
  );
}
