// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqZhz_oTdpu0i8nTFbtOTRFmPVRfiFywM',
    appId: '1:982102404489:web:54809a7d44d6b65c2e4558',
    messagingSenderId: '982102404489',
    projectId: 'workouttracker-387f6',
    authDomain: 'workouttracker-387f6.firebaseapp.com',
    storageBucket: 'workouttracker-387f6.firebasestorage.app',
    measurementId: 'G-ET8RVJMMEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA865Ca2e4i3dCJLBHkZOLqb4IyUA9Pe6A',
    appId: '1:982102404489:android:460d905feeee06f02e4558',
    messagingSenderId: '982102404489',
    projectId: 'workouttracker-387f6',
    storageBucket: 'workouttracker-387f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqyo0uxgCeH_fMvHThzQLWn0PWunVPBH4',
    appId: '1:982102404489:ios:a096d0bce4b711be2e4558',
    messagingSenderId: '982102404489',
    projectId: 'workouttracker-387f6',
    storageBucket: 'workouttracker-387f6.firebasestorage.app',
    iosBundleId: 'com.example.workoutTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqyo0uxgCeH_fMvHThzQLWn0PWunVPBH4',
    appId: '1:982102404489:ios:a096d0bce4b711be2e4558',
    messagingSenderId: '982102404489',
    projectId: 'workouttracker-387f6',
    storageBucket: 'workouttracker-387f6.firebasestorage.app',
    iosBundleId: 'com.example.workoutTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqZhz_oTdpu0i8nTFbtOTRFmPVRfiFywM',
    appId: '1:982102404489:web:b4acebcc472197522e4558',
    messagingSenderId: '982102404489',
    projectId: 'workouttracker-387f6',
    authDomain: 'workouttracker-387f6.firebaseapp.com',
    storageBucket: 'workouttracker-387f6.firebasestorage.app',
    measurementId: 'G-QSKHTWFD98',
  );
}